dist: focal
sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t maciej55/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maciej55/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-209479289647"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"